const list = [{
    "check": false,
    "id": 8,
    "name": "全部",
    "type": "func",
    "childNodes":[{
        "check": false,
        "childNodes": [{
            "check": false,
            "id": 8,
            "name": "查询",
            "type": "func"
        }, {
            "check": false,
            "id": 9,
            "name": "创建账户",
            "type": "func"
        }, {
            "check": false,
            "id": 10,
            "name": "编辑",
            "type": "func"
        }, {
            "check": false,
            "id": 11,
            "name": "删除",
            "type": "func"
        }, {
            "check": false,
            "id": 52,
            "name": "查看",
            "type": "func"
        }],
        "id": 13,
        "menuOrder": 1,
        "menuUrl": "/index/userManager",
        "name": "账户管理",
        "type": "menu"
    }, {
        "check": false,
        "id": 10,
        "name": "角色管理",
        "type": "menu"
    }, {
        "check": false,
        "id": 11,
        "name": "销售主体管理",
        "type": "menu"
    }, {
        "check": false,
        "childNodes": [{
            "check": false,
            "childNodes": [{
                "check": false,
                "id": 33,
                "name": "批量导入",
                "type": "func"
            }, {
                "check": false,
                "id": 44,
                "name": "查询",
                "type": "func"
            }, {
                "check": false,
                "id": 45,
                "name": "创建计划",
                "type": "func"
            }, {
                "check": false,
                "id": 46,
                "name": "下载导入模版",
                "type": "func"
            }, {
                "check": false,
                "id": 47,
                "name": "查看",
                "type": "func"
            }, {
                "check": false,
                "id": 48,
                "name": "下架",
                "type": "func"
            }, {
                "check": false,
                "id": 49,
                "name": "删除",
                "type": "func"
            }],
            "id": 15,
            "name": "全部",
            "type": "menu"
        }, {
            "check": false,
            "childNodes": [{
                "check": false,
                "id": 38,
                "name": "批量导入",
                "type": "func"
            }, {
                "check": false,
                "id": 53,
                "name": "创建计划",
                "type": "func"
            }, {
                "check": false,
                "id": 55,
                "name": "查询",
                "type": "func"
            }, {
                "check": false,
                "id": 56,
                "name": "下架",
                "type": "func"
            }, {
                "check": false,
                "id": 58,
                "name": "查看",
                "type": "func"
            }, {
                "check": false,
                "id": 60,
                "name": "删除",
                "type": "func"
            }, {
                "check": false,
                "id": 76,
                "name": "编辑",
                "type": "func"
            }],
            "id": 16,
            "name": "待上线",
            "type": "menu"
        }, {
            "check": false,
            "childNodes": [{
                "check": false,
                "id": 63,
                "name": "查看",
                "type": "func"
            }, {
                "check": false,
                "id": 64,
                "name": "下架",
                "type": "func"
            }, {
                "check": false,
                "id": 73,
                "name": "查询",
                "type": "func"
            }],
            "id": 17,
            "name": "投放中",
            "type": "menu"
        }, {
            "check": false,
            "childNodes": [{
                "check": false,
                "id": 65,
                "name": "查看",
                "type": "func"
            }, {
                "check": false,
                "id": 66,
                "name": "查询",
                "type": "func"
            }, {
                "check": false,
                "id": 67,
                "name": "下架",
                "type": "func"
            }],
            "id": 18,
            "name": "已撞线",
            "type": "menu"
        }, {
            "check": false,
            "childNodes": [{
                "check": false,
                "id": 68,
                "name": "查看",
                "type": "func"
            }, {
                "check": false,
                "id": 70,
                "name": "查询",
                "type": "func"
            }, {
                "check": false,
                "id": 74,
                "name": "编辑",
                "type": "func"
            }],
            "id": 19,
            "name": "已下架",
            "type": "menu"
        }, {
            "check": false,
            "childNodes": [{
                "check": false,
                "id": 71,
                "name": "查看",
                "type": "func"
            }, {
                "check": false,
                "id": 75,
                "name": "查询",
                "type": "func"
            }],
            "id": 20,
            "name": "已下线",
            "type": "menu"
        }],
        "id": 14,
        "name": "计划管理",
        "type": "menu"
    }, {
        "check": false,
        "childNodes": [{
            "check": false,
            "id": 25,
            "name": "查询",
            "type": "func"
        }, {
            "check": false,
            "id": 26,
            "name": "添加广告",
            "type": "func"
        }, {
            "check": false,
            "id": 27,
            "name": "查看",
            "type": "func"
        }, {
            "check": false,
            "id": 28,
            "name": "下架",
            "type": "func"
        }, {
            "check": false,
            "id": 29,
            "name": "删除",
            "type": "func"
        }],
        "id": 21,
        "name": "品牌广告",
        "type": "menu"
    }, {
        "check": false,
        "childNodes": [{
            "check": false,
            "childNodes": [{
                "check": false,
                "id": 30,
                "name": "查询",
                "type": "func"
            }, {
                "check": false,
                "id": 31,
                "name": "下载报表",
                "type": "func"
            }],
            "id": 23,
            "name": "销售主体数据概览",
            "pId": 22,
            "type": "menu"
        }, {
            "check": false,
            "childNodes": [{
                "check": false,
                "id": 32,
                "name": "查看",
                "type": "func"
            }, {
                "check": false,
                "id": 51,
                "name": "下载报表",
                "type": "func"
            }],
            "id": 24,
            "name": "账户数据概览",
            "pId": 22,
            "type": "menu"
        }, {
            "check": false,
            "childNodes": [{
                "check": false,
                "id": 34,
                "name": "查询",
                "type": "func"
            }, {
                "check": false,
                "id": 35,
                "name": "下载报表",
                "type": "func"
            }],
            "id": 25,
            "name": "计划明细概览",
            "pId": 22,
            "type": "menu"
        }, {
            "check": false,
            "childNodes": [{
                "check": false,
                "id": 36,
                "name": "查询",
                "type": "func"
            }, {
                "check": false,
                "id": 37,
                "name": "下载报表",
                "type": "func"
            }],
            "id": 26,
            "name": "品牌广告明细概览",
            "pId": 22,
            "type": "menu"
        }, {
            "check": false,
            "childNodes": [{
                "check": false,
                "id": 39,
                "name": "下载报表",
                "type": "func"
            }],
            "id": 27,
            "name": "投放分析",
            "pId": 22,
            "type": "menu"
        }],
        "id": 22,
        "name": "数据概览",
        "type": "menu"
    }, {
        "check": false,
        "childNodes": [{
            "check": false,
            "id": 40,
            "name": "查询",
            "type": "func"
        }, {
            "check": false,
            "id": 41,
            "name": "下载报表",
            "type": "func"
        }],
        "id": 28,
        "name": "收入查询",
        "type": "menu"
    }, {
        "check": false,
        "id": 29,
        "name": "下线提醒",
        "type": "menu"
    }, {
        "check": false,
        "childNodes": [{
            "check": false,
            "id": 61,
            "name": "上传",
            "type": "func"
        }, {
            "check": false,
            "id": 62,
            "name": "删除",
            "type": "func"
        }],
        "id": 31,
        "name": "发票合同管理",
        "type": "menu"
    }, {
        "check": false,
        "childNodes": [{
            "check": false,
            "id": 42,
            "name": "查看",
            "type": "func"
        }, {
            "check": false,
            "id": 43,
            "name": "查询",
            "type": "func"
        }],
        "id": 32,
        "name": "日志管理",
        "type": "menu"
    }, {
        "check": false,
        "id": 37,
        "name": "用户管理",
        "type": "menu"
    }]
}]
export default list;